INSERT INTO "DVD"."C_USERS" VALUES (
	NEXTVAL('DVD.SEQ_C_USERS'), 'Евгений', 'eugene', '12345',1
);
INSERT INTO "DVD"."C_USERS" VALUES (
	NEXTVAL('DVD.SEQ_C_USERS'), 'Елена', 'elena', '67890',1
);

INSERT INTO "DVD"."M_USER_ROLES" VALUES (
	'admin', 1
);
INSERT INTO "DVD"."M_USER_ROLES" VALUES (
	'user', 1
);
INSERT INTO "DVD"."M_USER_ROLES" VALUES (
	'user', 2
);

INSERT INTO "DVD"."R_DISKS" VALUES (
	NEXTVAL('DVD.SEQ_R_DISKS'), 'Рыбка Поньо на утесе', 1 
);
INSERT INTO "DVD"."R_DISKS" VALUES (
	NEXTVAL('DVD.SEQ_R_DISKS'), 'Крупная рыба', 1 
);
INSERT INTO "DVD"."R_DISKS" VALUES (
	NEXTVAL('DVD.SEQ_R_DISKS'), 'Жизнь как чудо', 1 
);
INSERT INTO "DVD"."R_DISKS" VALUES (
	NEXTVAL('DVD.SEQ_R_DISKS'), 'Грязные танцы', 2
);

INSERT INTO "DVD"."R_TAKEN_ITEMS" VALUES (
	NEXTVAL('DVD.SEQ_R_TAKEN_ITEMS'), 2, 1
);
