CREATE SCHEMA IF NOT EXISTS DVD;
SET SCHEMA DVD;

DROP SEQUENCE IF EXISTS DVD.SEQ_C_USERS;
CREATE SEQUENCE DVD.SEQ_C_USERS;

DROP SEQUENCE IF EXISTS DVD.SEQ_M_USER_ROLES;
CREATE SEQUENCE DVD.SEQ_M_USER_ROLES;

DROP TABLE IF EXISTS DVD.C_USERS;
CREATE TABLE DVD.C_USERS
( "USER_ID" NUMBER PRIMARY KEY,
  "USER_NAME" VARCHAR(50 CHAR) NOT NULL,
  "LOGIN" VARCHAR (50 CHAR) NOT NULL,
  "PASSWORD" VARCHAR(50 CHAR) NOT NULL,
  "ENABLED" NUMBER NOT NULL
);

DROP TABLE IF EXISTS DVD.M_USER_ROLES;
CREATE TABLE DVD.M_USER_ROLES
( "USER_ROLE" VARCHAR(50 CHAR) NOT NULL,
  "USER_USER_ID" NUMBER NOT NULL
);

DROP SEQUENCE IF EXISTS DVD.SEQ_R_DISKS;
CREATE SEQUENCE DVD.SEQ_R_DISKS;

DROP TABLE IF EXISTS DVD.R_DISKS;
CREATE TABLE DVD.R_DISKS
( "DISK_ID" NUMBER PRIMARY KEY,
  "MOVIE_TITLE" VARCHAR(255 CHAR) NOT NULL,
  "DISK_OWNER_ID" NUMBER NOT NULL
);

DROP SEQUENCE IF EXISTS DVD.SEQ_R_TAKEN_ITEMS;
CREATE SEQUENCE DVD.SEQ_R_TAKEN_ITEMS;

DROP TABLE IF EXISTS DVD.R_TAKEN_ITEMS;
CREATE TABLE DVD.R_TAKEN_ITEMS
( "ITEM_ID" NUMBER PRIMARY KEY,
  "USER_ID" NUMBER NOT NULL,
  "DISK_ID" NUMBER NOT NULL
);

