CREATE SCHEMA IF NOT EXISTS DVD;
SET SCHEMA DVD;

DROP SEQUENCE IF EXISTS DVD.SEQ_USERS;
CREATE SEQUENCE DVD.SEQ_USERS;

DROP SEQUENCE IF EXISTS DVD.SEQ_USER_ROLES;
CREATE SEQUENCE DVD.SEQ_USER_ROLES;

DROP TABLE IF EXISTS DVD.USERS;
CREATE TABLE DVD.USERS
( "USER_ID" NUMBER PRIMARY KEY,
  "USER_NAME" VARCHAR(50 CHAR) NOT NULL,
  "LOGIN" VARCHAR (50 CHAR) NOT NULL,
  "PASSWORD" VARCHAR(50 CHAR) NOT NULL,
  "ENABLED" NUMBER NOT NULL
);

DROP TABLE IF EXISTS DVD.USER_ROLES;
CREATE TABLE DVD.USER_ROLES
( "USER_ROLE" VARCHAR(50 CHAR) NOT NULL,
  "USER_USER_ID" NUMBER NOT NULL
);

DROP SEQUENCE IF EXISTS DVD.SEQ_DISKS;
CREATE SEQUENCE DVD.SEQ_DISKS;

DROP TABLE IF EXISTS DVD.DISKS;
CREATE TABLE DVD.DISKS
( "DISK_ID" NUMBER PRIMARY KEY,
  "MOVIE_ID" NUMBER NOT NULL,
  "DISK_OWNER_ID" NUMBER NOT NULL
);

DROP TABLE IF EXISTS DVD.MOVIES;
CREATE TABLE DVD.MOVIES
( "MOVIE_ID" NUMBER PRIMARY KEY,
  "POSTER_PATH" VARCHAR(50 CHAR),
  "TITLE" VARCHAR(100 CHAR) NOT NULL,
  "ORIGINAL_TITLE" VARCHAR(100 CHAR) NOT NULL,
  "OVERVIEW" VARCHAR (1000 CHAR) NOT NULL,
  "RELEASE_YEAR" NUMBER,
  "VOTE_AVERAGE" NUMBER
);

DROP SEQUENCE IF EXISTS DVD.SEQ_TAKEN_ITEMS;
CREATE SEQUENCE DVD.SEQ_TAKEN_ITEMS;

DROP TABLE IF EXISTS DVD.TAKEN_ITEMS;
CREATE TABLE DVD.TAKEN_ITEMS
( "ITEM_ID" NUMBER PRIMARY KEY,
  "USER_ID" NUMBER NOT NULL,
  "DISK_ID" NUMBER NOT NULL
);

