CREATE SCHEMA IF NOT EXISTS DVD;
SET SCHEMA DVD;

DROP SEQUENCE IF EXISTS DVD.SEQ_C_USERS;
CREATE SEQUENCE DVD.SEQ_C_USERS;

DROP TABLE IF EXISTS DVD.C_USERS;
CREATE TABLE DVD.C_USERS
( "USER_ID" NUMBER PRIMARY KEY,
  "USER_NAME" VARCHAR(50 CHAR) NOT NULL
);

DROP SEQUENCE IF EXISTS DVD.SEQ_R_DISKS;
CREATE SEQUENCE DVD.SEQ_R_DISKS;

DROP TABLE IF EXISTS DVD.R_DISKS;
CREATE TABLE DVD.R_DISKS
( "DISK_ID" NUMBER PRIMARY KEY,
  "MOVIE_TITLE" VARCHAR(255 CHAR) NOT NULL,
  "DISK_OWNER_ID" NUMBER NOT NULL
);
